FORMAT: 1A
HOST: http://localhost:port_number/

# BLSMicroservice

A microservice to centralize communication between our company and back office

## Account Details [/accounts/{accountNumber}]

+ Parameters
    + accountNumber (long) - BETA customer account number


### Provides information of the account based on account number [GET]

+ Response 200 (application/json)

        [
            {
                "accountnumber": 10089885,
                "rep": "HB01",
                "branch": "TPHB",
                "sub": "211",
                "firm": "001"
                "documentationCategory": 24,
                "accountType": 21,
                "birthdate": "0001-01-01T00:00:00.0000000-05:00",
                "primaryEmailAddress": "TEST@FOOBAR.COM"
                "numNameAddressLines": 4,
                "nameAndAddressLine1": "2511 NW 41ST STREET",
                "nameAndAddressLine2": "NEW",
                "nameAndAddressLine3": "6707 W NEWBERRY RD",
                "nameAndAddressLine4": "GAINESVILLE, FL, 32605",
                "nameAndAddressLine5": "GAINESVILLE, FL 32606-6630",
                "nameAndAddressLine6": null,
                "alphaKeys": null,
                "alphaKeys1": "TRADE PMR",
                "alphaKeys2": "DEV ACCOUNT",
                "alphaKeys3": "SUNDRY ACCOUNT HB01",
                "alphaKeys4": null,
                "irsNameAndAddressLines1": 1,
                "irsNameAndAddressLines2": 0,
                "taxId": null,
                "state": "FL"
                "country": null,
                "residentId": null,
                "province": null,
                "city": "GAINESVILLE",
                "zipCode": "32606",
                "zipPlus4Code": "6630",
                "homePhone": "8502618430",
                "homePhone2": null,
                "businessPhone": "8502618430",
                "businessPhone2": null,
                "cellPhone1": null,
                "cellPhone2": null,
                "otherPhone": "8502618430",
                "fax": null,
                "cashStandingInstruction": "4C",
                "secondaryCashStandingInstruction": null,
                "marginStandingInstructions": null,
                "dividendStandingInstructions": 3,
                "foreignStandingInstructions": null,
                "investmentObjective": 0,
                "optionInvestmentObjectiveType": 5,
                "mmfSweep": null,
                "checkWriting": false,
                "lastStatement": "2017-07-01T00:00:00.0000000-04:00",
                "openDate": "2008-06-25T00:00:00.0000000-04:00",
                "changeDate": "2017-07-26T00:00:00.0000000-04:00",
                "iraType": null,
                "iraBirthday": "0001-01-01T00:00:00.0000000-05:00",
                "iraFeeSchedule": null,
                "iraFeeStatus": null,
                "iraPrimarySecondary": null,
                "classificationCode": null,
                "tefra": true,
                "mmfSymbol": null,
                "disclosure": 1,
                "manageGroup": "FSRC",
                "oldAccountNumber": "TP10089885",
                "visaType": null,
                "wrap": null,
                "networkEligibleType": "3",
                "postage": 0,
                "docTransactionLevel": "1",
                "statementCode": "B",
                "productClass": "AAPP",
                "nav": 5,
                "accountDividendReinvestmentIndicator": 2,
                "employeeClassCode": null,
                "preventPrincipalTrade": false,
                "noConfirm": null,
                "accountTypeIndicator": null,
                "riskTolerance": null,
                "wrapManagerId": null,
                "accountStatus": null,
                "productType": "STANDARD BROKERAGE",
                "cookie": null
            }
        ]
        
## Assosciated Persons Inquiry [/accounts/{accountNumber}/associatedPersons]

+ Parameters
    + accountNumber (long) - BETA customer account number

### Provides a display of legal address and demographic information for individuals who are account holders or who are assosciated with an account [GET]

+ Response 200 (application/json)

        [
            {
                "name": "TRADE PMR",
                "accountNumber": 10089885,
                "homePhone": "3525555555",
                "taxId": null,
                "taxIdFormat": null,
                "zipCode": "32605",
                "firstName": "TRADE PMR",
                "lastName": null,
                "state": "FL",
                "city": "GAINESVILLE",
                "useZip4Switch": false,
                "birthdate": null,
                "emailAddress": "JPINCHOT@TRADEPMR.COM",
                "occupation": 3,
                "employerName": "MCTESTERSON FARMS",
                "employerAddress": "2511 NW 41ST ST ASDF",
                "employerCity": "GAINESVILLE",
                "employerState": "FL",
                "employerZip": "32606",
                "nameType": 1,
                "middleName": null,
                "nasdAffiliate": false,
                "employerUseZip4Switch": false,
                "primaryOwnerAssociation": 0,
                "customerType": 1,
                "addressLine1": "6707 W NEWBERRY RD",
                "addressLine2": null
            }
        ]

## Tax Lot Closed Holdings Inquiry [/accounts/{accountNumber}/taxlots/closed?{StartDate}&{EndDate}]

+ Parameters
    + accountNumber (long) - BETA customer account number
    + StartDate (DateTime) - Beginning date for a specific period of closed tax lot activity.
    + EndDate (DateTime) - End date for a specific period of closed tax lot activity.

### Provides information for closed tax lots for customer accounts at our firm [GET]

+ Response 200 (application/json) 

    {
        "taxLots": 
        [
            {
                "description": "AIRPORTS OF THAILAND ADR PUBLIC CO LTD-ADR",
                "securityType": 2,
                "percentGainLoss": -0.1615384615384615384615384615,
                "symbol": "AIPUY",
                "cusip": "00950R100",
                "securityNumber": 1054520,
                "name": "TRADE PMR",
                "quantity": 1,
                "closeAmount": 10.9,
                "closeDate": "2017-02-27T00:00:00.0000000-05:00",
                "closePrice": 10.9,
                "realized": -2.1,
                "shortTermGainOrLoss": -2.1,
                "longTermGainOrLoss": 0,
                "costAmount": 13,
                "openDate": "2017-02-23T00:00:00.0000000-05:00",
                "adjustedUnitCost": 0,
                "unitCost": 13,
                "term": "SHORT",
                "adjustedCost": 0,
                "cookie": null
            }
        ],
            "footer": 
            {
                "percentGainLoss": 0.0061170065443265357801359511,
                "closeAmount": 1271.42,
                "realized": 7.73,
                "shortTermGainOrLoss": -5.75,
                "longTermGainOrLoss": 13.48,
                "costAmount": 1263.69
            }
    }
    
## Account Demographics Inquiry [/accounts/{accountNumber}/demographics]

+ Parameters
    + accountNumber (long) - BETA customer account number

### Displays demographic information for customer accounts.  [GET]

+ Response 200 (application/json)

        {
            "accountNumber": 10089885,
            "birthdate": "0001-01-01T00:00:00.0000000-05:00",
            "spouseBirthdate": "0001-01-01T00:00:00.0000000-05:00",
            "gender": 0,
            "maritalStatus": 0,
            "emailAddress": "TEST@FOOBAR.COM",
            "dependents": 0,
            "retired": false,
            "incomeTaxBracket": 0,
            "businessNature": 0,
            "occupation": 3,
            "employerName": "MCTESTERSON FARMS",
            "employerAddress": "2511 NW 41ST ST ASDF",
            "employerCity": "GAINESVILLE",
            "employerState": "FL",
            "employerZip": "32606",
            "employerZipPlus4": null,
            "annualIncome": null,
            "netWorth": null,
            "liquidNetWorth": null,
            "investExperienceWithStocks": 0,
            "investExperienceWithOptions": 0,
            "investExperienceWithMutualFunds": 0,
            "investExperienceWithInsuranceAnnuities": 0,
            "investExperienceWithBonds": 0,
            "timeHorizon": null,
            "liquidity": null,
            "cookie": null
        }
        
## Account Valuation Inquiry [/accounts/{accountNumber}/balances]

+ Parameters
    + accountNumber (long) - BETA customer account number

### Displays all money balances in a customer's account.  [GET]

+ Response 200 (application/json)
        
        {
            "name": null,
            "rep": "HB01",
            "accountNumber": 10089885,
            "branch": "TPHB",
            "lastActivityDate": "2017-07-01T00:00:00.0000000-04:00",
            "primaryMmfName": null,
            "wrapPlanId": null,
            "pendingVisaCharges": 0,
            "cashBalance": 226.92,
            "foreignBalance": 0,
            "totalCashBalance": 226.92,
            "marginBalance": 0,
            "otherAccountTypesTotalBalance": 0,
            "dividendAndInterestBalance": 2.46,
            "totalMmfBalance": 0,
            "specialMiscellaneousAccountBalance": 0,
            "fundsAvailable": 226.92,
            "cashAccountMarketValue": 1503.9,
            "cashAccountForeignMarketValue": 0,
            "marginAccountLongMarketValue": 0,
            "marginAccountShortMarketValue": 0,
            "otherAccountTypesMarketValue": 0,
            "otherCashAccountsMarketValue": 0,
            "miscOutsideInvestmentsMarketValue": 0,
            "marginableSecuritiesCashAvailable": 751.93,
            "marginableSecuritiesMarketValue": 1503.9,
            "totalMarketValue": 1503.9,
            "fedCall": 0,
            "houseCall": 0,
            "dailyDebitInterest": 0,
            "mtdDebitInterest": 0,
            "marginAccountEquityPercentage": 0,
            "marginAccountTotalEquity": 0,
            "marginAccountCashAvailable": 0,
            "marginAccountBuyingPower": 0,
            "totalAccountValue": 1733.28,
            "commissionTotal": 0,
            "totalLongMarketValue": 1503.9,
            "todayMmfCreditDebit": 0,
            "balanceAsOfTradeDate": 226.92,
            "balanceAsOfSettleDate": 226.92,
            "tradingCash": 0,
            "freeAndClearBalanceAsOfSettleDate": 226.92,
            "freeCrMiscDr": 226.92,
            "nonShareholderAccruedMtdInterest": 0,
            "numberOfTradesTtm": 23,
            "totalCashWithoutBorrowing": 226.92,
            "frozenFundsForChecks": 0,
            "whenIssuedBalance": 0,
            "unconfirmedMfOrders": 0,
            "mmfBalances": {},
            "calculatedCashBalance": 226.92,
            "calculatedMarginAccountBuyingPower": 453.84,
            "cookie": null
        }
        
## Account Violation Inquiry [/accounts/{accountNumber}/violations]

+ Parameters
    + accountNumber (long) - BETA customer account number

###  Allows to monitor individualized violation information on customer accounts. [GET]

+ Response 200 (application/json)
        
        [
            {
                "accountNumber": 10089885,
                "specialHandlingCode": "80",
                "changed": "2017-07-14T00:00:00.0000000-04:00",
                "violations": null,
                "cookie": null
            }
        ]
        
## ACH Instruction Inquiry [/accounts/{accountNumber}/achInstructions]

+ Parameters
    + accountNumber (long) - BETA customer account number

### The ACH Instruction Inquiry enables the viewing of ACH instruction records. ACH instructions are used by brokerage firms to electronically transfer income balances, free credit money, and trading debits automatically to an individual's checking or savings account at his or her bank.  [GET]

+ Response 200 (application/json)
        
        [
            {
                "accountNumber": 10089885,
                "sub": 211,
                "source": "EFT",
                "openDate": "2017-05-24T00:00:00.0000000-04:00",
                "preNotificationDate": "2017-05-24T00:00:00.0000000-04:00",
                "effectiveDate": "2017-05-24T00:00:00.0000000-04:00",
                "abaRoutingNumber": "021000021",
                "customerName1": "PLAID CHECKING",
                "customerName2": null,
                "itemNumber": 1,
                "instructionStatus": "A",
                "bankAccountNumber": "9900001702",
                "bankAccountType": 0,
                "lastAchActivity": "0001-01-01T00:00:00.0000000-05:00",
                "hasOnDemandCredit": true,
                "hasOnDemandDebit": false,
                "bankName": "JPMORGAN CHASE BANK, NA",
                "customerName": "PLAID CHECKING"
            }
        ]
        
## Positions by Account Inquiry [/accounts/{accountNumber}/positions]

+ Parameters
    + accountNumber (long) - BETA customer account number

### Displays positions for a specific account. Information for each security includes market price, total long and short quantities and values.   [GET]

+ Response 200 (application/json)
        
        [
            {
                "symbol": "AET",
                "cusip": "00817Y108",
                "securityNumber": 1042822,
                "accountNumber": 10089885,
                "accountType": 1,
                "location": "SEG",
                "marginable": true,
                "marketPrice": 156.79,
                "value": 470.37,
                "quantity": 3,
                "percentOfTotal": null,
                "description": null,
                "securityType": 0,
                "quoteStatus": 0,
                "isLocked": false,
                "isMargin": false,
                "isMoneyMarketFund": false,
                "isCash": false,
                "cookie": null
            },
            {
                "symbol": "AMANX",
                "cusip": "022865109",
                "securityNumber": 1097612,
                "accountNumber": 10089885,
                "accountType": 1,
                "location": "SKF",
                "marginable": true,
                "marketPrice": 48.65,
                "value": 1.02,
                "quantity": 0.021,
                "percentOfTotal": null,
                "description": null,
                "securityType": 0,
                "quoteStatus": 0,
                "isLocked": false,
                "isMargin": false,
                "isMoneyMarketFund": false,
                "isCash": false,
                "cookie": null
            }
        ]